site_name: lernOS Problem strukturiert lösen Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen: 1-0-Grundlagen.md
    - Lernpfad: 2-0-Lernpfad.md
      - Was bringt Dich hierher: 2-1-was-bringt-dich-hierher.md
      - Das Problem beschreiben: 2-2-beschreibe-dein-problem-ausfuehrlich.md
      - Probleme einteilen: 2-3-probleme-lassen-sich-einteilen.md
      - Problemlösung im Team: 2-4-problemloesung-im-team.md
      - Korrekturmaßnahmen: 2-5-korrekturmassnahmen.md
      - Ursachenanalyse 1: 2-6-ursachenanalyse-methodenbaukasten-1.md
      - Ursachenanalyse 2: 2-7-ursachenanalyse-methodenbaukasten-2.md
      - Finden und Umsetzen von Lösungen: 2-8-finden-und-umsetzen-von-loesungen.md
      - Woher erkenne ich, dass eine Lösung erfolgreich ist: 2-9-woher-erkenne-ich-dass-eine-loesung-erfolgreich-ist.md
      - Transfer: 2-10-transfer.md
      - Feiern: 2-11-feiern.md
      - Retrospektive: 2-12-retrospektive.md
    - Anhang: 3-0-Anhang.md"

REM Delete Old Versions
echo Deleting old versions ...
del %filename%.*

REM Create Web Version (mkdocs)
echo Creating Web Version ...
mkdocs build

REM Create Microsoft Word Version (docx)
echo Creating Word version ...
pandoc metadata.yaml --from markdown -s --resource-path="./src" -F mermaid-filter --number-sections -V lang=de-de -o %filename%.docx %chapters%

REM Create HTML Version (html)
echo Creating HTML version ...
pandoc metadata.yaml --from markdown -s --resource-path="./src" -F mermaid-filter --number-sections -V lang=de-de -o %filename%.html %chapters%

REM Create PDF Version (pdf)
echo Creating PDF version ...
pandoc metadata.yaml --from markdown -s --resource-path="./src" -F mermaid-filter --template lernOS --number-sections --toc -V lang=de-de -o %filename%.pdf %chapters%

REM Create eBook Versions (epub, mobi)
echo Creating eBook versions ...
magick -density 300 %filename%.pdf[0] src/images/ebook-cover.jpg
magick mogrify -size 2500x2500 -resize 2500x2500 src/images/ebook-cover.jpg
magick mogrify -crop 1563x2500+102+0 src/images/ebook-cover.jpg
pandoc metadata.yaml --from markdown -s --resource-path="./src" -F mermaid-filter --epub-cover-image=src/images/ebook-cover.jpg --number-sections --toc -V lang=de-de -o %filename%.epub %chapters%
ebook-convert %filename%.epub %filename%.mobi

    - Anhang: 3-0-Anhang.md
    - Download:
#      - PDF-Version: https://github.com/cogneon/lernos-template/blob/master/de/lernOS-Template-Guide-de.pdf
#      - Word-Version: https://github.com/cogneon/lernos-template/blob/master/de/lernOS-Template-Guide-de.docx
#      - HTML-Version: https://github.com/cogneon/lernos-template/blob/master/de/lernOS-Template-Guide-de.html
#      - E-Book (epub): https://github.com/cogneon/lernos-template/blob/master/de/lernOS-Template-Guide-de.epub
#      - E-Book (mobi): https://github.com/cogneon/lernos-template/blob/master/de/lernOS-Template-Guide-de.mobi
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'bertvaneub/lernos-problem-solving'
repo_url: 'https://github.com/bertvaneub/lernos-template'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2
